<div class="row form-section">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
        <?php
        $form->setAttribute('action', $this->url('home'));
        $form->setAttribute('class', 'row');
        $form->prepare();
        echo $this->form()->openTag($form); ?>
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 row">
            <?php echo $this->formRow($form->get('content')); ?>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <?php echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 img-thumbnail">
        <table class="table table-responsive">
            <thead>
            <tr>
                <th>
                    created
                </th>
                <th>
                    text
                </th>
            </tr>
            </thead>
            <tbody id="messagesContainer">
            <?php foreach ($messages as $oneMessage): ?>
                <tr>
                    <td>
                        <?= $this->escapeHtml(date('Y-m-d H:i:s', $oneMessage->getCreatedAt())); ?>
                    </td>
                    <td>
                        <?= $this->escapeHtml($oneMessage->getContent()); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>