<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Simple Chat Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('stylesheets/screen.css'));
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body class="continer">
            <header class="text-center">
                <div class="class="col-lg-12 col-md-12 col-sm-12 col-xs-12"">
                <h1 class="h1 lead">
                    Simple Chat Test Project
                </h1>
                </div>
            </header>
            <section class="p-x-1">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <?= $this->content ?>
                </div>
            </section>
            <footer class="text-center">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <p>&copy; <?= date('Y') ?> Application  by Mariusz Matlak. All rights reserved.</p>
                </div>
            </footer>
        </div>
        <?= $this->inlineScript()->prependFile($this->basePath('js/message.index.js')); ?>
    </body>
</html>
